name: Mona Test
on:
  push:
    branches:
      - feat/tests
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.22.0]

    steps:
      # prepare env
      - name: update
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt-get -y clean
          DEBIAN_FRONTEND=noninteractive sudo apt-get -y autoremove
      - name: add node
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt install -y nodejs
          node -v
      - name: add npm
        run: |
          curl -L https://npmjs.org/install.sh | sudo sh
          DEBIAN_FRONTEND=noninteractive sudo apt install -y npm
          npm -v
      - name: add yarn
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt install -y yarn
      - name: npm install and npm test
        run: |
          npm i  --registry=https://registry.npmjs.org
          npm install -g @bytedance/mona-cli --registry=https://registry.npmjs.org
          npm run test
